### ISSUE TITLE
Finish week 2 vocab

### ISSUE THREAD

**Issue by baileyfosdick** [geanders/csu_msmb#31]
- Fix formatting of table
- Add Quizlet

**Comment by geanders** [comment]
I fixed the formatting of the table and added the Quizlet app into the post. 

I think the only thing left is to take out the "Sources cited" if you don't have any (or put any you used in that section).

**Comment by baileyfosdick** [comment]
Removed "sources cited".  How did you fix the table formatting?

**Comment by geanders** [comment]
@baileyfosdick : I just noticed that one of the terms this week is "statistical inference / up / statistical approach". I'm assuming the middle word should be something other than "up" and that some other letters might have gotten lost along the way (sorry, that totally could have been me with a rogue cut-and-paste!). If you know what that word should be, could you fix it? Otherwise, if we can't figure it out, I'll just take it out.

**Comment by baileyfosdick** [comment]
Actually "up" is the correct term.  It is bolded throughout the chapter.  I put all those terms together because they use them interchangeably in the text.

**Comment by geanders** [comment]
Oh my goodness. I wasn't familiar with that term in that context! Okay great, no typo to fix *and* I learned something---a win all around!
